// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ClearMessageBoxController from "./clear_message_box_controller"
application.register("clear-message-box", ClearMessageBoxController)

import GeolocationController from "./geolocation_controller"
application.register("geolocation", GeolocationController)
