name: Deploy with Capistrano

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.2
        bundler-cache: true
    - uses: miloserdow/capistrano-deploy@master
      with:
        target: production
        deploy_key: ${{ secrets.DEPLOY_ENC_KEY }}
