name: Deploy with Capistrano

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.0
        bundler-cache: true
    - uses: miloserdow/capistrano-deploy@master
      with:
        target: production
        deploy_key: ${{ secrets.DEPLOY_ENC_KEY }}
